umap_model:
    n_neighbors: 10
    n_components: 5
    min_dist: 0.0
    metric: cosine
    random_state: 42

hdbscan_model:
    min_cluster_size: 10
    metric: euclidean
    cluster_selection_method: eom
    prediction_data: True

vectorizer_model:
    stop_words: english
    min_df: 5

mmr_model:
    diversity: 0.3

topic_model:
    top_n_words: 10
    min_topic_size: 5
    verbose: True
    calculate_probabilities: True

unwanted_sections_header:
    - references
    - appendix
    - glossary
    - table of contents
    - acknowledgments
    - disclosure statement
    - author
    - contact
    - executive summary
    - introduction
    
entity_labels:
    - PERSON
    - ORG
    - DATE

phrase_mapping:
  genai: "generative AI"
  gen ai: "generative AI"
  generative ai: "generative AI"
  generative artificial intelligence: "generative AI"